import os

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.core.management.utils import get_random_secret_key

PROVIDERS = {
    "facebook": {
        "label": "Facebook",
        "backend": "social_core.backends.facebook.FacebookOAuth2",
        "url": "https://developers.facebook.com/apps/",
    },
    "twitter": {
        "label": "Twitter",
        "backend": "social_core.backends.twitter.TwitterOAuth",
        "url": "https://developer.twitter.com/en/portal/dashboard",
    },
    "github": {
        "label": "Github",
        "backend": "social_core.backends.github.GithubOAuth2",
        "url": "https://github.com/settings/applications/new",
    },
}


class Command(BaseCommand):
    help = "Interactively create the jukebox site configuration"

    def add_arguments(self, parser):
        parser.add_argument(
            "--force",
            action="store_true",
            help="Overwrite an existing settings_local.py",
        )

    def handle(self, *args, **options):
        target = os.path.join(settings.JUKEBOX_STORAGE_PATH, "settings_local.py")
        if os.path.exists(target) and not options["force"]:
            raise CommandError(f"{target} already exists, use --force to overwrite it")

        self.stdout.write("----------------------------------------------")
        self.stdout.write("-----    Welcome to the jukebox setup    -----")
        self.stdout.write("----------------------------------------------")
        self.stdout.write("")

        self.stdout.write("Page administrator")
        self.stdout.write("----------------------------------------------")
        admin_user = self.ask("\tName: ")
        admin_email = self.ask("\tE-mail: ")
        self.stdout.write("")

        self.stdout.write("Hosts")
        self.stdout.write("----------------------------------------------")
        self.stdout.write("\tHost names or IP addresses used to open the jukebox in the browser")
        hosts = input("\tComma separated [localhost,127.0.0.1]: ").strip()
        allowed_hosts = [h.strip() for h in hosts.split(",") if h.strip()] or [
            "localhost",
            "127.0.0.1",
        ]
        self.stdout.write("")

        authentication = self.read_authentication()

        with open(
            os.open(target, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600), "w", encoding="utf-8"
        ) as f:
            f.write(self.render(admin_user, admin_email, allowed_hosts, authentication))

        self.stdout.write(self.style.SUCCESS(f"Setup finished, configuration written to {target}"))
        self.stdout.write("----------------------------------------------")
        self.stdout.write("Next steps:")
        self.stdout.write("\tjukebox migrate")
        self.stdout.write("\tjukebox jukebox_adduser <username> --admin")
        self.stdout.write("\tjukebox jukebox_index --path=/path/to/library")

    def ask(self, prompt):
        value = ""
        while not value:
            value = input(prompt).strip()
        return value

    def read_authentication(self):
        self.stdout.write("Social login (optional)")
        self.stdout.write("----------------------------------------------")
        self.stdout.write(
            "Users can always log in with a local account, create one with "
            "'jukebox jukebox_adduser <username>'."
        )
        self.stdout.write(
            "Available providers: " + ", ".join(p["label"] for p in PROVIDERS.values())
        )
        self.stdout.write("")

        authentication = {}
        for name, provider in PROVIDERS.items():
            self.stdout.write(provider["label"])
            self.stdout.write(
                f"\t{provider['label']} authentication requires setup of an app on "
                f"{provider['url']}"
            )
            self.stdout.write(f"\tCallback URL: http(s)://<your host>/complete/{name}/")
            data = self.read_app_data(provider["label"])
            if data is not None:
                authentication[name] = data
            self.stdout.write("")

        return authentication

    def read_app_data(self, label):
        answer = input(f"\tUse {label} for authentication? [y/n] ").strip().lower()
        while answer not in ("y", "n"):
            answer = (
                input("\tInvalid answer, please enter 'y' for yes or 'n' for no: ").strip().lower()
            )

        if answer == "n":
            return None

        return {
            "key": self.ask(f"\t{label} app id: "),
            "secret": self.ask(f"\t{label} app secret: "),
        }

    def render(self, admin_user, admin_email, allowed_hosts, authentication):
        backends = ["django.contrib.auth.backends.ModelBackend"] + [
            PROVIDERS[name]["backend"] for name in authentication
        ]
        lines = [
            "# Generated by jukebox_setup",
            f"ADMINS = [({admin_user!r}, {admin_email!r})]",
            "",
            "DEBUG = False",
            f"ALLOWED_HOSTS = {allowed_hosts!r}",
            "",
            f"SECRET_KEY = {get_random_secret_key()!r}",
            "",
            f"AUTHENTICATION_BACKENDS = {backends!r}",
            f"SOCIAL_AUTH_ENABLED_BACKENDS = {list(authentication)!r}",
            "",
        ]
        for name, data in authentication.items():
            lines.append(f"SOCIAL_AUTH_{name.upper()}_KEY = {data['key']!r}")
            lines.append(f"SOCIAL_AUTH_{name.upper()}_SECRET = {data['secret']!r}")
            lines.append("")
        return "\n".join(lines)
