# Generated by Django 5.2.17 on 2026-09-23 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["Title"],
            },
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["Name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["Name"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Pid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=200)),
                ("Year", models.IntegerField(blank=True, null=True)),
                ("Length", models.IntegerField()),
                ("Filename", models.CharField(max_length=1000)),
                (
                    "Album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jukebox_core.album",
                    ),
                ),
                (
                    "Artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jukebox_core.artist",
                    ),
                ),
                (
                    "Genre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jukebox_core.genre",
                    ),
                ),
            ],
            options={
                "ordering": ["Title", "Artist", "Album"],
            },
        ),
        migrations.CreateModel(
            name="Queue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Created", models.DateTimeField(auto_now_add=True)),
                ("User", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                (
                    "Song",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jukebox_core.song",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Created", models.DateTimeField(auto_now_add=True)),
                (
                    "User",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "Song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jukebox_core.song",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "history",
                "ordering": ["-Created"],
            },
        ),
        migrations.CreateModel(
            name="Favourite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Created", models.DateTimeField(auto_now_add=True)),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "Song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jukebox_core.song",
                    ),
                ),
            ],
            options={
                "ordering": ["-Created"],
                "unique_together": {("Song", "User")},
            },
        ),
    ]
